name: short_video
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  chewie: ^1.3.4
  dio: ^4.0.6
  event_bus: ^2.0.0
  flutter_easyloading: ^3.0.5
  crypto: ^3.0.2
  convert: ^3.0.2
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/gif/
    - assets/png/
    - assets/svg/
    - assets/svg/home/
    - assets/svg/profile/
    - assets/png/tabbar/
    - assets/png/home/
    - assets/png/profile/
    - assets/png/other/
